--- 
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action
        with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout
      - name: Test
<<<<<<< HEAD
        run: docker compose run --rm app sh -c "python manage.py"
=======
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
>>>>>>> 1aa3333e077e061441c5c2e6160895e024ce33a8
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
  
      
    
